"""empty message

Revision ID: 791cd7d80402
Revises: 
Create Date: 2017-05-02 16:01:24.803337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791cd7d80402'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic',
    sa.Column('aadfyear', sa.Integer(), nullable=False),
    sa.Column('cp', sa.Integer(), nullable=False),
	sa.Column('estimationmethod', sa.String(length=30), nullable=True),
	sa.Column('estimationmethoddetailed', sa.String(length=200), nullable=True),
	sa.Column('region', sa.String(length=30), nullable=True),
	sa.Column('localauthority', sa.String(length=30), nullable=True),
	sa.Column('road', sa.String(length=10), nullable=True),
	sa.Column('roadcategory', sa.String(length=10), nullable=True),
	sa.Column('easting', sa.String(length=10), nullable=True),
	sa.Column('northing', sa.String(length=10), nullable=True),
	sa.Column('startjunction', sa.String(length=100), nullable=True),
	sa.Column('endjunction', sa.String(length=100), nullable=True),
    sa.Column('linklengthkm', sa.Float(), nullable=True),
    sa.Column('linklengthmiles', sa.Float(), nullable=True),
    sa.Column('pedalcycles', sa.Integer(), nullable=True),
    sa.Column('motorcycles', sa.Integer(), nullable=True),
    sa.Column('carstaxis', sa.Integer(), nullable=True),
    sa.Column('busescoaches', sa.Integer(), nullable=True),
    sa.Column('lightgoodsvehicles', sa.Integer(), nullable=True),
    sa.Column('v2axlerigidhgv', sa.Integer(), nullable=True),
    sa.Column('v3axlerigidhgv', sa.Integer(), nullable=True),
    sa.Column('v4or5axlerigidhgv', sa.Integer(), nullable=True),
    sa.Column('v3or4axleartichgv', sa.Integer(), nullable=True),
	sa.Column('v5axleartichgv', sa.Integer(), nullable=True),
	sa.Column('v6ormoreaxleartichgv', sa.Integer(), nullable=True),
	sa.Column('allhgvs', sa.Integer(), nullable=True),
	sa.Column('allmotorvehicles', sa.Integer(), nullable=True),
  #  sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('aadfyear', 'cp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic')
    # ### end Alembic commands ###
